In [1]:
from cdapython import Q
from global_settings import integration_host, integration_table

a = (
    Q("subject_identifier_system = 'GDC'")
    .ORDER_BY("days_to_birth:-1")
    .subject.run(show_sql=True, host=integration_host, table=integration_table)
    .to_dataframe()
)
a

Getting results from database

,subject_id,subject_identifier,species,sex,race,ethnicity,days_to_birth,subject_associated_project,vital_status,days_to_death,cause_of_death
0,C3N-03093,"[{'system': 'GDC', 'value': 'C3N-03093'}, {'sy...",homo sapiens,female,not reported,not reported,0,"[CPTAC-3, cptac_lscc, CPTAC3-Discovery]",Not Reported,NaN,None
1,C3N-03092,"[{'system': 'GDC', 'value': 'C3N-03092'}, {'sy...",homo sapiens,male,not reported,not reported,0,"[CPTAC-3, cptac_lscc, CPTAC3-Discovery]",Not Reported,NaN,None
2,C3N-02252,"[{'system': 'GDC', 'value': 'C3N-02252'}, {'sy...",homo sapiens,female,white,not hispanic or latino,0,"[CPTAC-3, cptac_lscc, CPTAC3-Discovery]",Not Reported,NaN,None
3,C3N-02714,"[{'system': 'GDC', 'value': 'C3N-02714'}, {'sy...",homo sapiens,male,not reported,not reported,-8551,"[cptac_hnscc, CPTAC-3, CPTAC3-Discovery]",Alive,NaN,None
4,C3N-02783,"[{'system': 'GDC', 'value': 'C3N-02783'}, {'sy...",homo sapiens,female,not reported,not reported,-8889,"[cptac_gbm, CPTAC-3, CPTAC3-Discovery]",Alive,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...
95,TCGA-A2-A0EX,"[{'system': 'GDC', 'value': 'TCGA-A2-A0EX'}, {...",homo sapiens,female,white,not hispanic or latino,-16858,"[tcga_brca, CPTAC-TCGA, TCGA-BRCA]",Alive,NaN,None
96,C3L-00161,"[{'system': 'GDC', 'value': 'C3L-00161'}, {'sy...",homo sapiens,female,white,hispanic or latino,-16864,"[CPTAC-3, cptac_ucec, CPTAC3-Discovery]",Alive,NaN,Not Reported
97,C3N-00244,"[{'system': 'GDC', 'value': 'C3N-00244'}, {'sy...",homo sapiens,male,white,not hispanic or latino,-16873,"[cptac_ccrcc, CPTAC-3, CPTAC3-Discovery]",Alive,NaN,Not Reported
98,TCGA-AA-A010,"[{'system': 'GDC', 'value': 'TCGA-AA-A010'}, {...",homo sapiens,female,not reported,not reported,-16922,"[TCGA-COAD, CPTAC-TCGA, tcga_coad]",Alive,NaN,None
99,C3N-02000,"[{'system': 'GDC', 'value': 'C3N-02000'}, {'sy...",homo sapiens,female,not reported,not reported,-16924,"[cptac_luad, CPTAC-3, CPTAC3-Discovery]",Alive,NaN,None